### ISSUE TITLE
possible broken link in docs

### ISSUE THREAD

**Issue by rniksch** [jasonumiker/clair-ecs-fargate#1]
the following link provided in the readme returns a http 404.
You may have changed the repo structure or removed this file without updating the links in the readme.

https://github.com/jasonumiker/ghost-ecs-fargate/blob/master/ghost-container/buildspec_clair.yml

**Comment by jasonumiker** [comment]
You're right - I refactored that into two seperate repos (this Clair one and a seperate Ghost example one) and decomissioned the original and forgot to update the link. I fixed it. Thanks for pointing it out!
